### ISSUE TITLE
Feature request : set backend priority

### ISSUE THREAD

**Issue by rgarrigue** [ansible-community/molecule-containers#12]
Hello

The current behavior is to pick docker if available, otherwise podman. I'ld like to do the reverse. 

I believe allowing users to define a precedence order would be for the best: for example "podman > docker" would mean "if podman is available then use podman, otherwise docker". Defaulting to the current behavior defined as "docker > podman".

Best regards,

**Comment by ssbarnea** [comment]
A patch to implement this is more than welcomed.
